### ISSUE TITLE
Scrolling notes

### ISSUE THREAD

**Issue by richardeszes** [byhestia/springseed#161]
Hi,

I like this application, but I have a problem with Springseed. If I create several notes I can't reach last notes because they are unreachable. The last notes sticking out from the window.

Version: 2.0
OS: Ubuntu 14.04 LTS
DE: Unity

**Comment by eguevara2012** [comment]
Hello!
I installed version 2.0 in Ubuntu 14.04 and this bug continue. The last notes sticking out from the window.
Thanks!

**Comment by dsawa** [comment]
Confirmed, Ubuntu 14.04 LTS, Springseed 2.0 (64-bit) downloaded from the getspringseed.com.
Can not scroll notes. The only way to get to the note that is at the bottom is to maximize window.
