### ISSUE TITLE
Issue with springseed

### ISSUE THREAD

**Issue by Brendonslash** [byhestia/springseed#166]
Error: module "ast-types" not found from "/home/dheeraj/springseed/node_modules/analytics-                  node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy- agent/node_modules/pac-resolver/node_modules/degenerator/index.js"
      at notFound (/home/dheeraj/springseed/node_modules/browserify/index.js:812:15)
      at /home/dheeraj/springseed/node_modules/browserify/index.js:762:23
      at /home/dheeraj/springseed/node_modules/browserify/node_modules/browser-    resolve/index.js:184:24
      at /home/dheeraj/springseed/node_modules/browserify/node_modules/resolve/lib/async.js:50:14
      at process     (/home/dheeraj/springseed/node_modules/browserify/node_modules/resolve/lib/async.js:119:43)
      at /home/dheeraj/springseed/node_modules/browserify/node_modules/resolve/lib/async.js:128:21
      at load      (/home/dheeraj/springseed/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
      at /home/dheeraj/springseed/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
      at /home/dheeraj/springseed/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
      at Object.oncomplete (fs.js:107:15)

    make: *** [public/application.js] Error 1

This is the error I get when I do make I'm not familiar with ruby so please tell the solution thanks.

**Comment by nitishch** [comment]
I think your system is configured to access Github using `http://` but not with `git://` protocol. `npm`, as you can see in the error messages is trying to use `git://` protocol. So, run the command

    git config --global url."https://".insteadOf git://

and then run the installation commands again or better start with a fresh install :wink:
