### ISSUE TITLE
Minor bug when adding categories

### ISSUE THREAD

**Issue by fonorobert** [byhestia/springseed#175]
After I add a category and try to add another, the name of the previously added category can be seen in the right-click menu instead of the text "Add category"

springseed 2.0 x64 on ubuntu 14.4 with xfce

Screenshot: 
![springseed](https://cloud.githubusercontent.com/assets/6963710/4780079/49a174ac-5c57-11e4-9abf-359f5b706d2e.png)

**Comment by nitishch** [comment]
Yeah. This is strange. 

Further details of this bug:
1. Label "add category" disappears in every notebook. Not just in the notebook in which a category was added.
2. On restarting the app, "add category" reappears. 

OS: Ubuntu 14.04LTS
architecture: i686

**Comment by zackp30** [comment]
Thanks @nitishch!
