### ISSUE TITLE
how to run springseed based on source code

### ISSUE THREAD

**Issue by CharellKing** [byhestia/springseed#182]
i wan't add baidu network disk (a kind of network disk in china) in springseed to sync notes

**Comment by zackp30** [comment]
Hi! Sorry for the delay, I didn't see this issue on my email.

Anyway, the compilation instructions are within the README, you need atom-shell to run it.

`ATOM_SHELL_DIRECTORY/atom SPRINGSEED_DIRECTORY` should do it.
