### ISSUE TITLE
Scrolling notes in Ubuntu 14.04

### ISSUE THREAD

**Issue by eguevara2012** [byhestia/springseed#186]
Hello!
I installed version 2.0 in Ubuntu 14.04 and the last notes sticking out from the window. The bug of scrolling notes persist.
Thanks!

**Comment by nitishch** [comment]
Can you post a screenshot?

**Comment by ryanvade** [comment]
Same on Arch Linux. I can't scroll through the note list.  Which is causing some issues. 
![screenshot from 2015-03-03 11 14 36](https://cloud.githubusercontent.com/assets/1910293/6467846/806b8eec-c196-11e4-8dc3-1c90f530fcc6.png)

**Comment by nitishch** [comment]
@ryanvade @eguevara2012 Did you compile from the source or download the .deb files?

**Comment by ryanvade** [comment]
@nitishch  The AUR package is built with the deb file. https://aur.archlinux.org/packages/sp/springseed/PKGBUILD

**Comment by eguevara2012** [comment]
@nitishch Hello! I installed with .deb file from http://getspringseed.com/

**Comment by nitishch** [comment]
That settles it. I think .deb file is not up to date with this source. See #169. @zackp30 @michealharker

**Comment by zackp30** [comment]
Really sorry I haven't been paying attention. I will go build the deb now. Thanks!

**Comment by zackp30** [comment]
I made a basic zip file for now. I will try and contact @michealharker so I can find out how to make a proper `.deb`. See README on this repository for more information about the zip file. And thanks for the patience. :smile:

**Comment by nitishch** [comment]
Does the script work properly? When you run it for the first time, it downloads `atom.zip` into a folder `atom` and without unzipping it tries to run `./atom`. But there is not file named `atom`.

**Comment by eguevara2012** [comment]
The repository will be updated? We can run an "upgrade" command and receive the corrections.

**Comment by nitishch** [comment]
Yeah. Once the `.deb` file is made, you can run an "upgrade".

**Comment by zackp30** [comment]
Oops, sorry, redownload springseed.zip... I made a mistake.

**Comment by hollowdoor** [comment]
I have downloaded the .deb file from the springseed site. The scrolling problem still persists.

My download is from last week. I just encountered the problem today, and tried to upgrade to fix the problem. No dice.
