### ISSUE TITLE
Focus of view of note is changed to beginning of note after 'Paste'

### ISSUE THREAD

**Issue by ankitp94** [byhestia/springseed#190]
I started using springseed today. GooD UI !

Whenever I paste some text in my note, the focus of the note is changed to beginning of the note.
Then, I have to go the end of my note again to continue editing it.

With a long enough note and continuous use of copy-paste, it gets annoying.

**Comment by nitishch** [comment]
It has been fixed. You can use fixed version by downloading the updated source files or `git pull`ing the changes.

**Comment by ankitp94** [comment]
Thanx :+1:
