### ISSUE TITLE
Mac OS X Version Compilation Attempt

### ISSUE THREAD

**Issue by kman14367** [byhestia/springseed#194]
Hi,
I attempted to compile a version of Springseed on Mac OS X and when I run it with electron, I get this window:
![screen shot 2015-06-09 at 11 30 24 am](https://cloud.githubusercontent.com/assets/7730389/8064939/45f284f8-0e9b-11e5-85dc-ee88e3dc832e.png)
The plus button does not work, and clicking and dragging in the white area makes my cursor into the text-editing one.
P.S. I'm not sure if this is actually an issue, or just something useful to know when porting Springseed.

**Comment by nitishch** [comment]
This usually happens to me when I make a mistake in `application.js` file. Do you observe anything strange in the output? (start Springseed using a terminal and it prints out some output)

**Comment by kman14367** [comment]
Only this, but I see it in lots of different applications:
`Electron[19116] <Error>: The function ‘CGContextErase’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.`

**Comment by kman14367** [comment]
Also, I managed to use the built version that you provided for download just fine.

**Comment by nitishch** [comment]
@kman14367  Finally, what was the problem behind that weird UI? Also, I think you can close this issue now.
