### ISSUE TITLE
Is it possible to run Springseed in a browser without Atom?

### ISSUE THREAD

**Issue by ViktorNova** [byhestia/springseed#204]
Can Springseed in a browser without Atom? 
I am curious, as Atom is quite heavy. Thanks!

**Comment by zackp30** [comment]
Atom is an editor, we use the base of Atom known as Electron. I don't believe Electron is heavy at all.

**Comment by zackp30** [comment]
We are also working on Springseed 3 which is a web-based (read: online) application.

**Comment by michealharker** [comment]
I am thinking about a native client for Linux sometime, maybe you can help test it out sometime?

**Comment by ViktorNova** [comment]
I did mean Electron, I apologize. It is only heavy in the sense that it runs in it's own version of Chromium which I was under the impression uses a few hundred megs of RAM just by itself, but I am excited to hear there is a web version in the works! Is any of this available right now?

@michealharker - I would be very happy to assist in testing out a Linux native client!
