### ISSUE TITLE
MW_CLASS of Springseed is "Atom"

### ISSUE THREAD

**Issue by miko007** [byhestia/springseed#205]
`MW_CLASS` of Springseed is *"Atom"*, which causes confusion on several docks and panels. Could you change it to something like *"Springseed"*?
That would be nice. I would have made a pull request, but i didn't find the occurence in the sourcecode.

#### Steps to reproduce
```bash
xprop WM_CLASS
(then click on springseed-window)
WM_CLASS(STRING) = "atom", "Atom"
```

**Comment by zackp30** [comment]
Are you using my bundle of springseed known as "springseed.zip" from apertron.net? I've realized the script inside of it uses an ancient version of electron, I will fix this now.

**Comment by zackp30** [comment]
Forgot to elaborate, the issue was fixed in atom-shell (aka Electron) back in November.

**Comment by zackp30** [comment]
Updating Springseed and node_modules in the process.

This is very long overdue, sorry everyone.

**Comment by zackp30** [comment]
Fixed. See README.
