### ISSUE TITLE
Unusable :(

### ISSUE THREAD

**Issue by s777s** [byhestia/springseed#206]
I like springseed, it looks stylish and simple.
But many users have a few languages on keyboard, and it is well-known, that 2 standard methods of changing keyboard layout are "Ctrl+Shift" and "Alt+Shift"/
When I type some text in Springseed and try to change layout - appears menu and I can't continue typing.
I think - that is very big issue for international users, springseed becomes almost unusable when typing a lot of text and changing layout often...
May I change that behavoir in some config file for now?

**Comment by melamity** [comment]
I'm bundling all issues under #210 for bugs such as these - is this a issue with locale, like, your language inputs?
